"""
train.py — Phase 2: Model Training
====================================
Loads model/landmarks.csv (generated by preprocess.py),
trains a Random Forest classifier, evaluates it, and
exports the trained model + label encoder to model/asl_model.pkl.

Why Random Forest?
  - Works excellently on tabular data (our 63 landmark features)
  - Fast to train (minutes, not hours)
  - Naturally handles multi-class (29 ASL classes)
  - Gives feature importance — useful for debugging
  - Tiny exported model (~500KB vs 50MB+ for a CNN)

Run from the backend/ directory:
  python model/train.py
"""

import os
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH   = os.path.join(BASE_DIR, "model", "landmarks.csv")
MODEL_PATH = os.path.join(BASE_DIR, "model", "asl_model.pkl")


def load_data():
    print(f"Loading {CSV_PATH} ...")
    df = pd.read_csv(CSV_PATH)
    print(f"  Rows    : {len(df)}")
    print(f"  Classes : {sorted(df['label'].unique())}")
    print(f"  Shape   : {df.shape}")

    X = df.drop(columns=["label"]).values   # (N, 63) landmark features
    y = df["label"].values                  # (N,)    class strings

    return X, y


def train():
    X, y = load_data()

    # ── Encode string labels → integers (A=0, B=1, … Z=25, del=26, …) ────────
    le = LabelEncoder()
    y_enc = le.fit_transform(y)
    print(f"\nLabel mapping: {dict(zip(le.classes_, le.transform(le.classes_)))}")

    # ── Train / validation split  (80% train, 20% val) ───────────────────────
    X_train, X_val, y_train, y_val = train_test_split(
        X, y_enc,
        test_size=0.2,
        random_state=42,
        stratify=y_enc,   # keeps class proportions equal in both splits
    )
    print(f"\nTrain samples : {len(X_train)}")
    print(f"Val   samples : {len(X_val)}")

    # ── Train Random Forest ───────────────────────────────────────────────────
    print("\nTraining Random Forest ...")
    clf = RandomForestClassifier(
        n_estimators=100,   # 100 decision trees voted together
        max_depth=None,     # let trees grow until leaves are pure
        n_jobs=-1,          # use all CPU cores
        random_state=42,
        verbose=1,
    )
    clf.fit(X_train, y_train)

    # ── Evaluate on validation set ────────────────────────────────────────────
    print("\nEvaluating ...")
    y_pred = clf.predict(X_val)
    acc    = accuracy_score(y_val, y_pred)

    print(f"\n{'='*60}")
    print(f"  Validation Accuracy : {acc * 100:.2f}%")
    print(f"{'='*60}")

    # ── Save model first so a successful train always lands ──────────────────
    bundle = {"model": clf, "label_encoder": le}
    joblib.dump(bundle, MODEL_PATH)
    print(f"\nModel saved to : {MODEL_PATH}")

    # ── Per-class report (pass explicit labels so missing classes don't crash)
    print("\nPer-class report:")
    all_label_ids = list(range(len(le.classes_)))
    print(
        classification_report(
            y_val, y_pred,
            labels=all_label_ids,
            target_names=le.classes_,
            zero_division=0,
        )
    )

    # ── Top 10 most important landmark features ───────────────────────────────
    importances = clf.feature_importances_
    feature_names = [f"{axis}{i}" for i in range(21) for axis in ("x", "y", "z")]
    top10 = np.argsort(importances)[-10:][::-1]
    print("Top 10 landmark features:")
    for idx in top10:
        print(f"  {feature_names[idx]:<6}  importance: {importances[idx]:.4f}")

    import os
    size_kb = os.path.getsize(MODEL_PATH) / 1024
    print(f"Model size     : {size_kb:.1f} KB")
    print("\nPhase 2 complete — ready for Phase 3 (FastAPI backend).")


if __name__ == "__main__":
    train()
